In [140]:
import numpy as np
import pandas as pd
from skmultilearn.problem_transform import BinaryRelevance
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.tree import DecisionTreeClassifier

   

def train():
    train = pd.read_csv('./data/train_file_test.csv',sep=';',index_col=0,header=None)
    test = pd.read_csv('./data/test_file_test.csv',sep=';',index_col=0,header=None)
    classes = pd.read_csv('./data/PRClasses.csv',sep=';',index_col=0,header=None)

    ids = test.index

    cls = [data[0].split('-') for data in classes.values]
    print(cls)
    mlb = MultiLabelBinarizer()
    cls = mlb.fit_transform(cls)
    classes = pd.DataFrame(cls,index=classes.index)
    #classes.to_csv('/Users/fd252/Documents/Cursos3/NAU/Research2/Python/data/classesfdp.csv', encoding='utf-8', header=False, index=False, sep=',')    
    

    X_train = train.values  
    X_test = test.values
    y_train = classes.loc[train.index].values
    y_test = classes.loc[test.index].values

    clf = BinaryRelevance(classifier=DecisionTreeClassifier(), require_dense = [False, True])
    clf.fit(X_train,y_train)
    
    probability = clf.predict_proba(X_test).toarray()
    predict = clf.predict(X_test).toarray()

    predict = pd.DataFrame(predict,index=ids)
    probability = pd.DataFrame(probability,index=ids)

    predict.to_csv('./data/predict_file.csv')
    probability.to_csv('./data/probability_file.csv')
    



In [141]:
train()

[['Throws', 'Logging', 'UI', 'UserPreferences', 'Utils', 'DataStructure', 'IO', 'Network'], ['IO', 'Utils', 'Throws', 'Logging', 'Network', 'UI', 'UserPreferences', 'DataStructure'], ['DataStructure', 'Utils'], ['Utils', 'TextUtility', 'IO', 'DataStructure'], ['Concurrency', 'Logging', 'DataStructure'], ['IO', 'Network', 'UserPreferences', 'Logging', 'DataStructure', 'UI', 'Throws', 'Utils', 'Dependency'], ['DataStructure', 'IO', 'Logging', 'UI', 'Dependency', 'Utils'], ['IO', 'Utils', 'DataStructure', 'Logging'], ['DataStructure', 'Utils'], ['Logging', 'Data', 'DataStructure', 'XML'], ['Utils'], ['Utils', 'TextUtility', 'DataStructure'], ['Utils', 'DataStructure'], ['DataStructure', 'Network', 'Utils', 'UI', 'IO', 'Logging', 'Throws', 'UserPreferences'], ['IO', 'Network', 'UI', 'DataStructure', 'Throws', 'Logging', 'UserPreferences', 'Utils'], ['Network', 'DataStructure', 'Logging', 'UI', 'UserPreferences', 'IO', 'Utils', 'Throws'], ['DataStructure', 'UserPreferences', 'Throws', 'Logg

/Users/fd252/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:26: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike
/Users/fd252/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:27: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike


ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [136]:
train = pd.read_csv('./data/train_file.csv',sep=';',index_col=0,header=None)
test = pd.read_csv('./data/test_file.csv',sep=';',index_col=0,header=None)
classes = pd.read_csv('./data/PRClasses.csv',sep=';',index_col=0,header=None)

    

In [137]:
ids = test.index

cls = [data[0].split('-') for data in classes.values]

mlb = MultiLabelBinarizer()
cls = mlb.fit_transform(cls)
print(cls)
classes = pd.DataFrame(cls,index=classes.index)
#classes.to_csv('/Users/fd252/Documents/Cursos3/NAU/Research2/Python/data/classesfdp.csv', encoding='utf-8', header=False, index=False, sep=',')    

classes


[[0 0 1 0 1 1 1 0 1 1 1 1 0]
 [0 0 1 0 1 1 1 0 1 1 1 1 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 0 1 0 0 1 0 0 0 1 0]
 [1 0 1 0 0 1 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 1 0 1 1 1 1 0]
 [0 0 1 1 1 1 0 0 0 1 0 1 0]
 [0 0 1 0 1 1 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0]
 [0 1 1 0 0 1 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 1 0 0 0 1 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 0 1 1 1 0 1 1 1 1 0]
 [0 0 1 0 1 1 1 0 1 1 1 1 0]
 [0 0 1 0 1 1 1 0 1 1 1 1 0]
 [0 0 1 0 1 1 1 0 1 1 1 1 0]
 [0 0 1 0 1 1 1 0 1 1 1 1 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 1 1 0 0 1 0 1 0]]


0  1  2  3  4  5  6  7  8  9  10  11  12
0                                           
1   0  0  1  0  1  1  1  0  1  1   1   1   0
7   0  0  1  0  1  1  1  0  1  1   1   1   0
10  0  0  1  0  0  0  0  0  0  0   0   1   0
11  0  0  1  0  1  0  0  1  0  0   0   1   0
15  1  0  1  0  0  1  0  0  0  0   0   0   0
18  0  0  1  1  1  1  1  0  1  1   1   1   0
19  0  0  1  1  1  1  0  0  0  1   0   1   0
22  0  0  1  0  1  1  0  0  0  0   0   1   0
24  0  0  1  0  0  0  0  0  0  0   0   1   0
27  0  1  1  0  0  1  0  0  0  0   0   0   1
29  0  0  0  0  0  0  0  0  0  0   0   1   0
31  0  0  1  0  0  0  0  1  0  0   0   1   0
32  0  0  1  0  0  0  0  0  0  0   0   1   0
35  0  0  1  0  1  1  1  0  1  1   1   1   0
43  0  0  1  0  1  1  1  0  1  1   1   1   0
44  0  0  1  0  1  1  1  0  1  1   1   1   0
45  0  0  1  0  1  1  1  0  1  1   1   1   0
46  0  0  1  0  1  1  1  0  1  1   1   1   0
47  0  0  1  0  0  0  0  0  0  0   0   0   0
48  0  0  1  0  1  1  1  0  0  1   0   1   0

In [138]:
X_train = train.values  
X_test = test.values
y_train = classes.loc[train.index].values
y_test = classes.loc[test.index].values

clf = BinaryRelevance(classifier=DecisionTreeClassifier(), require_dense = [False, True])
fit = clf.fit(X_train,y_train)


print(X_test)

[[0.288741 0.266286 0.246043 0.246043 0.246043 0.246043 0.246043 0.246043
  0.246043 0.246043 0.246043 0.246043 0.246043 0.246043 0.246043 0.246043
  0.246043 0.213029 0.212955 0.212955]
 [0.270664 0.270664 0.202533 0.202533 0.188898 0.188898 0.188898 0.188898
  0.188898 0.188898 0.188898 0.188898 0.188898 0.188898 0.188898 0.188898
  0.188898 0.188898 0.188898 0.188898]
 [0.25272  0.246043 0.246043 0.246043 0.246043 0.246043 0.246043 0.246043
  0.246043 0.246043 0.246043 0.246043 0.246043 0.246043 0.246043 0.246043
  0.220015 0.220015 0.220015 0.18954 ]
 [0.312738 0.238982 0.238982 0.238982 0.238982 0.238982 0.238982 0.232221
  0.232221 0.232221 0.232221 0.232221 0.232221 0.232221 0.232221 0.232221
  0.232221 0.232221 0.232221 0.232221]
 [0.407639 0.302252 0.302252 0.302252 0.302252 0.302252 0.302252 0.302252
  0.302252 0.302252 0.276686 0.276686 0.276686 0.276686 0.276686 0.276686
  0.276686 0.276686 0.148118 0.148118]
 [0.327091 0.327091 0.282631 0.282631 0.282631 0.282631 0.282631 

In [139]:
probability = clf.predict_proba(X_test).toarray()
#probability = clf.predict_proba(X_test)
#for i in range (len(probability)):
 #   print("x=%s, predicted = %s" %(X_test[i],probability[i]) )

predict = clf.predict(X_test).toarray()

predict = pd.DataFrame(predict,index=ids)
probability = pd.DataFrame(probability,index=ids)

predict.to_csv('./data/predict_file.csv')
probability.to_csv('./data/probability_file.csv')

In [125]:
classes.columns.values


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [133]:
X_test.shape

(16, 20)

In [127]:
y_train.shape

(16, 25)

In [128]:
y_test.shape

(16, 25)

In [134]:
X_train.shape

(16, 20)