In [140]:
import numpy as np
import pandas as pd
from skmultilearn.problem_transform import BinaryRelevance
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.tree import DecisionTreeClassifier

   

def train():
    train = pd.read_csv('./data/train_file_test.csv',sep=';',index_col=0,header=None)
    test = pd.read_csv('./data/test_file_test.csv',sep=';',index_col=0,header=None)
    classes = pd.read_csv('./data/PRClasses.csv',sep=';',index_col=0,header=None)

    ids = test.index

    cls = [data[0].split('-') for data in classes.values]
    print(cls)
    mlb = MultiLabelBinarizer()
    cls = mlb.fit_transform(cls)
    classes = pd.DataFrame(cls,index=classes.index)
    #classes.to_csv('/Users/fd252/Documents/Cursos3/NAU/Research2/Python/data/classesfdp.csv', encoding='utf-8', header=False, index=False, sep=',')    
    

    X_train = train.values  
    X_test = test.values
    y_train = classes.loc[train.index].values
    y_test = classes.loc[test.index].values

    clf = BinaryRelevance(classifier=DecisionTreeClassifier(), require_dense = [False, True])
    clf.fit(X_train,y_train)
    
    probability = clf.predict_proba(X_test).toarray()
    predict = clf.predict(X_test).toarray()

    predict = pd.DataFrame(predict,index=ids)
    probability = pd.DataFrame(probability,index=ids)

    predict.to_csv('./data/predict_file.csv')
    probability.to_csv('./data/probability_file.csv')
    



In [142]:
train()

[['Throws', 'Logging', 'UI', 'User Preferences', 'Utils', 'Data Structure', 'IO', 'Network'], ['IO', 'Utils', 'Throws', 'Logging', 'Network', 'UI', 'User Preferences', 'Data Structure'], ['Data Structure', 'Utils'], ['Utils', 'Text Utility', 'IO', 'Data Structure'], ['Concurrency', 'Logging', 'Data Structure'], ['IO', 'Network', 'User Preferences', 'Logging', 'Data Structure', 'UI', 'Throws', 'Utils', 'Dependency'], ['Data Structure', 'IO', 'Logging', 'UI', 'Dependency', 'Utils'], ['IO', 'Utils', 'Data Structure', 'Logging'], ['Data Structure', 'Utils'], ['Logging', 'Data', 'Data Structure', 'XML'], ['Utils'], ['Utils', 'Data Structure'], ['Data Structure', 'Network', 'Utils', 'UI', 'IO', 'Logging', 'Throws', 'User Preferences'], ['IO', 'Network', 'UI', 'Data Structure', 'Throws', 'Logging', 'User Preferences', 'Utils'], ['Network', 'Data Structure', 'Logging', 'UI', 'User Preferences', 'IO', 'Utils', 'Throws'], ['Data Structure', 'User Preferences', 'Throws', 'Logging', 'Network', 'IO

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

In [180]:
train = pd.read_csv('./data/train_file_20.csv',sep=';',index_col=0,header=None)
test = pd.read_csv('./data/test_file_20.csv',sep=';',index_col=0,header=None)
classes = pd.read_csv('./data/PRClasses_20.csv',sep=';',index_col=0,header=None)

    

In [181]:
ids = test.index

cls = [data[0].split('-') for data in classes.values]

mlb = MultiLabelBinarizer()
cls = mlb.fit_transform(cls)
print(cls)
classes = pd.DataFrame(cls,index=classes.index)
#classes.to_csv('/Users/fd252/Documents/Cursos3/NAU/Research2/Python/data/classesfdp.csv', encoding='utf-8', header=False, index=False, sep=',')    

classes


[[0 0 1 0 1 1 1 0 1 1 1 1 0]
 [0 0 1 0 1 1 1 0 1 1 1 1 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 0 1 0 0 1 0 0 0 1 0]
 [1 0 1 0 0 1 0 0 0 0 0 0 0]
 [0 0 1 1 1 1 1 0 1 1 1 1 0]
 [0 0 1 1 1 1 0 0 0 1 0 1 0]
 [0 0 1 0 1 1 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0]
 [0 1 1 0 0 1 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 1 0 0 0 1 0]
 [0 0 1 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 0 1 1 1 0 1 1 1 1 0]
 [0 0 1 0 1 1 1 0 1 1 1 1 0]
 [0 0 1 0 1 1 1 0 1 1 1 1 0]
 [0 0 1 0 1 1 1 0 1 1 1 1 0]
 [0 0 1 0 1 1 1 0 1 1 1 1 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 1 1 1 0 0 1 0 1 0]]


0  1  2  3  4  5  6  7  8  9  10  11  12
0                                           
1   0  0  1  0  1  1  1  0  1  1   1   1   0
7   0  0  1  0  1  1  1  0  1  1   1   1   0
10  0  0  1  0  0  0  0  0  0  0   0   1   0
11  0  0  1  0  1  0  0  1  0  0   0   1   0
15  1  0  1  0  0  1  0  0  0  0   0   0   0
18  0  0  1  1  1  1  1  0  1  1   1   1   0
19  0  0  1  1  1  1  0  0  0  1   0   1   0
22  0  0  1  0  1  1  0  0  0  0   0   1   0
24  0  0  1  0  0  0  0  0  0  0   0   1   0
27  0  1  1  0  0  1  0  0  0  0   0   0   1
29  0  0  0  0  0  0  0  0  0  0   0   1   0
31  0  0  1  0  0  0  0  1  0  0   0   1   0
32  0  0  1  0  0  0  0  0  0  0   0   1   0
35  0  0  1  0  1  1  1  0  1  1   1   1   0
43  0  0  1  0  1  1  1  0  1  1   1   1   0
44  0  0  1  0  1  1  1  0  1  1   1   1   0
45  0  0  1  0  1  1  1  0  1  1   1   1   0
46  0  0  1  0  1  1  1  0  1  1   1   1   0
47  0  0  1  0  0  0  0  0  0  0   0   0   0
48  0  0  1  0  1  1  1  0  0  1   0   1   0

In [182]:
X_train = train.values  
X_test = test.values
y_train = classes.loc[train.index].values
y_test = classes.loc[test.index].values

clf = BinaryRelevance(classifier=DecisionTreeClassifier(), require_dense = [False, True])
fit = clf.fit(X_train,y_train)


print(X_test)

[[0.353003 0.353003 0.353003 0.353003 0.353003 0.353003 0.331714 0.331714
  0.331714 0.331714 0.226419 0.11321  0.11321  0.11321  0.11321  0.11321
  0.11321  0.11321  0.11321  0.11321 ]
 [0.320943 0.267261 0.267261 0.267261 0.267261 0.267261 0.267261 0.267261
  0.267261 0.267261 0.267261 0.267261 0.267261 0.267261 0.267261 0.187217
  0.160471 0.160471 0.160471 0.160471]
 [0.277217 0.277217 0.277217 0.277217 0.277217 0.277217 0.277217 0.277217
  0.277217 0.277217 0.277217 0.277217 0.248723 0.248723 0.14471  0.14471
  0.14471  0.072355 0.072355 0.072355]
 [0.288741 0.266286 0.246043 0.246043 0.246043 0.246043 0.246043 0.246043
  0.246043 0.246043 0.246043 0.246043 0.246043 0.246043 0.246043 0.246043
  0.246043 0.213029 0.212955 0.212955]
 [0.270664 0.270664 0.202533 0.202533 0.188898 0.188898 0.188898 0.188898
  0.188898 0.188898 0.188898 0.188898 0.188898 0.188898 0.188898 0.188898
  0.188898 0.188898 0.188898 0.188898]
 [0.25272  0.246043 0.246043 0.246043 0.246043 0.246043 0.246043 0.

In [183]:
probability = clf.predict_proba(X_test).toarray()
#probability = clf.predict_proba(X_test)
#for i in range (len(probability)):
 #   print("x=%s, predicted = %s" %(X_test[i],probability[i]) )

predict = clf.predict(X_test).toarray()

predict = pd.DataFrame(predict,index=ids)
probability = pd.DataFrame(probability,index=ids)

predict.to_csv('./data/predict_file.csv')
probability.to_csv('./data/probability_file.csv')

In [184]:
classes.columns.values


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [185]:
X_test.shape

(19, 20)

In [186]:
y_train.shape

(22, 13)

In [187]:
y_test.shape

(19, 13)

In [188]:
X_train.shape

(22, 20)