In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import f1_score, average_precision_score

In [2]:


def metric():
    columns = ['Accuracy','F-Score','AUC-PR']

    #predictions = pd.read_csv('./data/predict_file1x4.csv',header=0,dtype=int,index_col=0)
    predictions = pd.read_csv('./data/predict_file_2x2NBS.csv',header=0,dtype=int,index_col=0)
    y_pred = predictions.values
    probabilities = pd.read_csv('./data/probability_file_2x2NBS.csv',header=0,dtype=float,index_col=0)
    y_proba = probabilities.values

    true = pd.read_csv('./data/PRClassesNoBlankSpaces.csv',sep=';',index_col=0,header=None).loc[predictions.index]
    values = [x[0].split('-') for x in true.values]
    mlb = MultiLabelBinarizer()
    y_true = mlb.fit_transform(values)
    
    #Accuracy
    acc_ml = accuracy_ml(y_pred,y_true)
    #F1-Score
    fmeasure_score = f1_score(y_pred,y_true, average='micro')
    #AUC-PR
    pr_score = average_precision_score(y_true,y_proba,average='micro')

    arr = [acc_ml,fmeasure_score,pr_score]

    df = pd.DataFrame([arr],columns=columns)

    print(df)

def accuracy_ml(y_pred,y_true):
    y = y_true == 1
    y_t = [[index for index, value in enumerate(data) if value == 1] for data in y_true]
    y_p = [[index for index, value in enumerate(data) if value == 1] for data in y_pred]
    acc = 0
    for i in range(len(y_t)):
        s,t = set(y_t[i]),set(y_p[i])
        union = s.union(t)
        intersection = s.intersection(t)
        acc += (len(intersection)/len(union))
    return acc/len(y_t)

In [3]:
metric()

   Accuracy   F-Score    AUC-PR
0  0.365915  0.527593  0.385294


In [4]:
## for debug below! 

In [5]:

def accuracy_ml(y_pred,y_true):
    y = y_true == 1
    y_t = [[index for index, value in enumerate(data) if value == 1] for data in y_true]
    y_p = [[index for index, value in enumerate(data) if value == 1] for data in y_pred]
    acc = 0
    for i in range(len(y_t)):
        s,t = set(y_t[i]),set(y_p[i])
        union = s.union(t)
        intersection = s.intersection(t)
        acc += (len(intersection)/len(union))
    return acc/len(y_t)



In [6]:
columns = ['Accuracy','F-Score','AUC-PR']

#predictions = pd.read_csv('./data/predict_file1x4.csv',header=0,dtype=int,index_col=0)
predictions = pd.read_csv('./data/predict_file_tudo_30NBS.csv',header=0,dtype=int,index_col=0)
y_pred = predictions.values
probabilities = pd.read_csv('./data/probability_file_tudo_30NBS.csv',header=0,dtype=float,index_col=0)
y_proba = probabilities.values

In [7]:
predictions.shape

(492, 25)

In [8]:
predictions

0.1  1  2  3  4  5  6  7  8  9  ...  15  16  17  18  19  20  21  22  23  \
0                                     ...                                       
3778    0  0  0  1  1  0  1  0  0  0  ...   0   0   0   1   0   0   0   0   1   
3783    0  0  0  0  1  0  0  0  0  0  ...   0   0   0   1   0   0   0   0   0   
3784    0  0  0  0  1  0  0  0  0  0  ...   0   0   0   0   0   0   1   0   1   
3785    0  0  0  1  1  1  0  0  0  0  ...   0   1   0   1   0   1   1   0   1   
3789    0  0  0  0  1  0  0  0  1  0  ...   0   1   0   1   0   1   0   0   1   
...   ... .. .. .. .. .. .. .. .. ..  ...  ..  ..  ..  ..  ..  ..  ..  ..  ..   
5706    0  0  0  1  1  0  0  0  1  0  ...   0   1   0   0   0   0   1   0   1   
5710    0  0  0  0  0  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1   
5715    0  0  0  1  1  0  0  0  1  0  ...   0   0   0   0   0   0   1   0   1   
5716    0  0  0  0  1  0  0  0  0  0  ...   0   0   0   0   0   0   0   0   1   
5717    0  0  0  0  1  0  0  0  1  0  ...   0   1   0   1   0   0   1   0   1   

      24  
0         
3778   0  
3783   0  
3784   0  
3785   0  
3789   0  
...   ..  
5706   0  
5710   0  
5715   0  
5716   0  
5717   0  

[492 rows x 25 columns]

In [9]:
probabilities.shape

(492, 25)

In [10]:
probabilities

0.1    1     2    3    4    5    6    7    8    9  ...   15   16   17  \
0                                                          ...                  
3778.0  0.0  0.0  0.00  1.0  1.0  0.0  1.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3783.0  0.0  0.0  0.00  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3784.0  0.0  0.0  0.00  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3785.0  0.0  0.0  0.25  1.0  1.0  1.0  0.0  0.0  0.0  0.0  ...  0.0  1.0  0.0   
3789.0  0.0  0.0  0.00  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  1.0  0.0   
...     ...  ...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
5706.0  0.0  0.0  0.00  1.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  1.0  0.0   
5710.0  0.0  0.0  0.00  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
5715.0  0.0  0.0  0.00  1.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.0   
5716.0  0.0  0.0  0.00  0.0  1.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
5717.0  0.0  0.0  0.00  0.0  1.0  0.0  0.0  0.0  1.0  0.0  ...  0.0  1.0  0.0   

         18   19   20   21   22   23   24  
0                                          
3778.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  
3783.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  
3784.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  
3785.0  1.0  0.0  1.0  1.0  0.0  1.0  0.0  
3789.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  
...     ...  ...  ...  ...  ...  ...  ...  
5706.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  
5710.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
5715.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  
5716.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
5717.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  

[492 rows x 25 columns]

In [11]:
true = pd.read_csv('./data/PRClassesNoBlankSpaces.csv',sep=';',index_col=0,header=None).loc[predictions.index]


In [12]:
true

1
0                                                      
3778          Utils-DataStructure-Network-IO-Logging-UI
3783  Throws-Logging-IO-DataStructure-Network-Utils-...
3784          Logging-Network-Utils-UI-IO-DataStructure
3785          IO-UI-Utils-DataStructure-Network-Logging
3789                                   UI-DataStructure
...                                                 ...
5706          Logging-Utils-IO-DataStructure-UI-Network
5710                                              Utils
5715  Test-HTTP-IO-Network-Utils-Logging-DataStructu...
5716          IO-Network-Logging-UI-DataStructure-Utils
5717  Network-Logging-Database-Utils-UI-DataStructur...

[492 rows x 1 columns]

# 

In [13]:
values = [x[0].split('-') for x in true.values]
mlb = MultiLabelBinarizer()
y_true = mlb.fit_transform(values)

In [14]:
values

[['Utils', 'DataStructure', 'Network', 'IO', 'Logging', 'UI'],
 ['Throws',
  'Logging',
  'IO',
  'DataStructure',
  'Network',
  'Utils',
  'UserPreferences',
  'UI'],
 ['Logging', 'Network', 'Utils', 'UI', 'IO', 'DataStructure'],
 ['IO', 'UI', 'Utils', 'DataStructure', 'Network', 'Logging'],
 ['UI', 'DataStructure'],
 ['Logging', 'Utils', 'IO', 'Network', 'UI', 'DataStructure'],
 ['DataStructure',
  'Throws',
  'Logging',
  'TextUtility',
  'Utils',
  'UI',
  'IO',
  'Dependency'],
 ['IO'],
 ['DataStructure', 'Logging', 'IO'],
 ['Utils', 'DataStructure', 'IO'],
 ['Utils',
  'Network',
  'DataStructure',
  'IO',
  'UserPreferences',
  'Logging',
  'Throws',
  'UI'],
 ['Logging', 'Utils', 'Throws', 'DataStructure'],
 ['Utils', 'DataStructure', 'Logging', 'TextUtility', 'IO', 'UI'],
 ['Utils', 'DataStructure', 'IO', 'Test'],
 ['Test', 'DataStructure', 'Utils', 'UI', 'IO'],
 ['DataStructure', 'UI', 'Utils', 'IO'],
 ['UI', 'Network', 'Utils', 'Logging', 'IO'],
 ['Dependency',
  'Data',
  

In [15]:
y_true

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 1, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0]])

In [16]:
type(y_true)

numpy.ndarray

In [17]:
y_true.shape

(492, 25)

In [18]:
y_proba


array([[0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [19]:
type(y_proba)

numpy.ndarray

In [20]:
y_proba.shape

(492, 25)

In [21]:
y_pred

array([[0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0]])

In [22]:
type(y_pred)

numpy.ndarray

In [23]:
y_pred.shape

(492, 25)

In [24]:
y_pred[1,]

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0])

In [25]:
#Accuracy
acc_ml = accuracy_ml(y_pred,y_true)

In [26]:
#F1-Score
fmeasure_score = f1_score(y_pred,y_true, average='micro')

In [27]:
#AUC-PR
pr_score = average_precision_score(y_true,y_proba,average='micro')


In [28]:
arr = [acc_ml,fmeasure_score,pr_score]

df = pd.DataFrame([arr],columns=columns)

print(df)

   Accuracy   F-Score    AUC-PR
0   0.36724  0.530254  0.388506


In [29]:
y = y_true == 1
y_t = [[index for index, value in enumerate(data) if value == 1] for data in y_true]
y_p = [[index for index, value in enumerate(data) if value == 1] for data in y_pred]


In [30]:
y_t

[[4, 8, 11, 14, 21, 23],
 [4, 8, 11, 14, 20, 21, 22, 23],
 [4, 8, 11, 14, 21, 23],
 [4, 8, 11, 14, 21, 23],
 [4, 21],
 [4, 8, 11, 14, 21, 23],
 [4, 6, 8, 11, 19, 20, 21, 23],
 [8],
 [4, 8, 11],
 [4, 8, 23],
 [4, 8, 11, 14, 20, 21, 22, 23],
 [4, 11, 20, 23],
 [4, 8, 11, 19, 21, 23],
 [4, 8, 18, 23],
 [4, 8, 18, 21, 23],
 [4, 8, 21, 23],
 [8, 11, 14, 21, 23],
 [3, 4, 6, 8, 11, 14, 18, 19, 21, 23],
 [4, 8, 11, 14, 18, 21, 23],
 [2, 4, 8, 11, 14, 23],
 [4, 23],
 [4, 8, 11, 21, 23],
 [3, 4, 8, 11, 14, 23],
 [2, 3, 4, 8, 11, 14, 21, 23],
 [2, 4, 8, 11, 14, 23],
 [4, 6, 8, 11, 16, 18, 21, 23],
 [4, 18, 21],
 [4, 6, 19, 21, 23],
 [23],
 [8, 11, 14, 21, 23],
 [4, 23],
 [4, 18],
 [4, 8, 11, 14, 21, 23],
 [8, 18, 23],
 [4, 8, 14, 18, 21, 23],
 [19],
 [4, 23],
 [6, 21, 23],
 [2, 4, 8, 11, 14, 21, 23],
 [4, 18, 23],
 [4, 8, 11, 14, 21, 23],
 [3, 4, 7, 8, 11, 14, 18, 23],
 [4, 8, 23],
 [4, 11, 16, 21, 23],
 [4, 8, 11, 14, 20, 21, 22, 23],
 [3, 4, 8, 11, 23],
 [4, 8, 11, 21, 23],
 [4, 8, 11, 14, 23],

In [31]:
y_p

[[3, 4, 6, 11, 14, 18, 23],
 [4, 10, 18],
 [4, 11, 21, 23],
 [3, 4, 5, 11, 16, 18, 20, 21, 23],
 [4, 8, 16, 18, 20, 23],
 [4, 11, 16, 20, 23],
 [3, 4, 8, 11, 14, 18, 21, 23, 24],
 [4, 6, 8, 23],
 [4, 8, 11, 13, 14, 15, 16, 22, 23, 24],
 [4, 11, 14, 21],
 [4, 18, 23],
 [4, 18],
 [4, 8, 18, 23],
 [3, 4, 6, 11, 14, 16, 18, 23],
 [3, 4, 8, 11, 14, 17, 20, 21, 23],
 [3, 4, 5, 14, 18, 23],
 [3, 4, 8, 16, 18, 21, 23],
 [4, 6, 23],
 [4, 8, 14, 18],
 [4, 18, 23],
 [4],
 [4],
 [4, 8, 18, 23],
 [4, 8, 11, 18, 23],
 [3, 4, 11, 14, 21, 23],
 [3, 4, 5, 8, 14, 16, 17, 18, 22, 23],
 [4, 8, 11, 18, 23],
 [4, 8, 11, 21, 22],
 [1, 4, 11, 16, 23],
 [1, 2, 4, 8, 11, 13, 14, 20, 23],
 [4, 11, 18, 23],
 [4, 6, 8, 21, 23],
 [4, 5, 11, 21, 23],
 [2, 3, 4, 6, 7, 8, 11, 14, 15, 16, 17, 18, 19, 21, 23, 24],
 [4, 8, 21, 23],
 [4, 11, 14, 21, 22, 23],
 [4, 6, 11, 16, 18, 19, 21, 22],
 [4, 5, 8, 11, 14, 15, 16, 20, 21, 23],
 [21, 23],
 [4, 8, 11, 14, 21, 23],
 [4, 5, 11, 14, 20],
 [4, 8, 18, 23],
 [4, 5, 8, 18, 21, 

In [34]:
y_true[0]

array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0])

In [35]:
true.head()


1
0                                                      
3778          Utils-DataStructure-Network-IO-Logging-UI
3783  Throws-Logging-IO-DataStructure-Network-Utils-...
3784          Logging-Network-Utils-UI-IO-DataStructure
3785          IO-UI-Utils-DataStructure-Network-Logging
3789                                   UI-DataStructure

In [36]:
true.iloc[0]

1    Utils-DataStructure-Network-IO-Logging-UI
Name: 3778, dtype: object

In [37]:
true1 = true.reset_index()

In [38]:
true1.iloc[0,0]

3778

In [39]:
#F1-Score
fmeasure_score = f1_score(y_pred[0],y_true[0], average='micro')

In [40]:
fmeasure_score

0.8000000000000002

In [41]:
#AUC-PR
pr_score = average_precision_score(y_true[0],y_proba[0],average='micro')


In [42]:
pr_score

0.46095238095238095

In [43]:
type(true1)

pandas.core.frame.DataFrame

In [44]:
## individual metrics for PR 

In [45]:
from array import array
acc = array("f")
fm = array("f")
pr = array("f")
dataout = []
for i in range(len(y_t)):
    s,t = set(y_t[i]),set(y_p[i])
    union = s.union(t)
    intersection = s.intersection(t)
    acc.append(len(intersection)/len(union))
    
    fmeasure_score = f1_score(y_pred[i],y_true[i], average='micro')
    fm.append(fmeasure_score)
    
    pr_score = average_precision_score(y_true[i],y_proba[i],average='micro')
    pr.append(pr_score)
    
    print ('PR - Accuracy - F-measure - Precision: ', true1.iloc[i,0], " - ", acc[i], "- ", fmeasure_score, " - ", pr_score )
    dataout.append( (true1.iloc[i,0], acc[i], fmeasure_score,  pr_score )) 
df_out = pd.DataFrame(dataout, columns = ['pr','acc','f-measure','precision']) 
#df_out.to_csv('./data/PRmetrics.csv', encoding='utf-8', header=False, index=False, sep=',')    
df_out.to_csv('./data/PRmetrics2x2NBS.csv', encoding='utf-8', index=False, sep=',')    
np.savetxt(r'./data/PRmetrics2x2NBS.txt', df_out.values, fmt='%s', delimiter=',')
        

PR - Accuracy - F-measure - Precision:  3778  -  0.4444444477558136 -  0.8000000000000002  -  0.46095238095238095
PR - Accuracy - F-measure - Precision:  3783  -  0.10000000149011612 -  0.64  -  0.3216666666666667
PR - Accuracy - F-measure - Precision:  3784  -  0.6666666865348816 -  0.92  -  0.8733333333333333
PR - Accuracy - F-measure - Precision:  3785  -  0.3636363744735718 -  0.72  -  0.3762962962962963
PR - Accuracy - F-measure - Precision:  3789  -  0.1428571492433548 -  0.76  -  0.12333333333333332
PR - Accuracy - F-measure - Precision:  3790  -  0.375 -  0.8000000000000002  -  0.42
PR - Accuracy - F-measure - Precision:  3798  -  0.4166666567325592 -  0.72  -  0.6267916865742953
PR - Accuracy - F-measure - Precision:  3800  -  0.25 -  0.88  -  0.25
PR - Accuracy - F-measure - Precision:  3801  -  0.30000001192092896 -  0.72  -  0.3
PR - Accuracy - F-measure - Precision:  3806  -  0.1666666716337204 -  0.8000000000000002  -  0.16333333333333333
PR - Accuracy - F-measure - Preci

PR - Accuracy - F-measure - Precision:  4311  -  0.30000001192092896 -  0.72  -  0.3742857142857143
PR - Accuracy - F-measure - Precision:  4312  -  0.625 -  0.88  -  0.6352380952380953
PR - Accuracy - F-measure - Precision:  4313  -  0.25 -  0.76  -  0.25
PR - Accuracy - F-measure - Precision:  4314  -  0.3333333432674408 -  0.76  -  0.37
PR - Accuracy - F-measure - Precision:  4317  -  0.699999988079071 -  0.88  -  0.7205555555555556
PR - Accuracy - F-measure - Precision:  4326  -  0.6666666865348816 -  0.92  -  0.7466666666666666
PR - Accuracy - F-measure - Precision:  4327  -  0.1111111119389534 -  0.68  -  0.3425
PR - Accuracy - F-measure - Precision:  4333  -  0.4000000059604645 -  0.64  -  0.76
PR - Accuracy - F-measure - Precision:  4335  -  0.125 -  0.72  -  0.125
PR - Accuracy - F-measure - Precision:  4336  -  0.6666666865348816 -  0.92  -  0.9523809523809523
PR - Accuracy - F-measure - Precision:  4337  -  0.3333333432674408 -  0.92  -  0.3333333333333333
PR - Accuracy - F-

PR - Accuracy - F-measure - Precision:  4799  -  0.3333333432674408 -  0.76  -  0.32125
PR - Accuracy - F-measure - Precision:  4801  -  0.5 -  0.92  -  0.58
PR - Accuracy - F-measure - Precision:  4803  -  0.1666666716337204 -  0.8000000000000002  -  0.16666666666666666
PR - Accuracy - F-measure - Precision:  4806  -  0.3333333432674408 -  0.68  -  0.3466666666666667
PR - Accuracy - F-measure - Precision:  4807  -  0.375 -  0.8000000000000002  -  0.42857142857142855
PR - Accuracy - F-measure - Precision:  4813  -  0.2857142984867096 -  0.8000000000000002  -  0.38222222222222224
PR - Accuracy - F-measure - Precision:  4815  -  0.3636363744735718 -  0.72  -  0.6033333333333334
PR - Accuracy - F-measure - Precision:  4818  -  0.6000000238418579 -  0.92  -  0.6025
PR - Accuracy - F-measure - Precision:  4822  -  0.5 -  0.8399999999999999  -  0.5771428571428572
PR - Accuracy - F-measure - Precision:  4823  -  0.1666666716337204 -  0.8000000000000002  -  0.26
PR - Accuracy - F-measure - Pre

PR - Accuracy - F-measure - Precision:  5354  -  0.5 -  0.88  -  0.5
PR - Accuracy - F-measure - Precision:  5355  -  0.75 -  0.92  -  0.83
PR - Accuracy - F-measure - Precision:  5356  -  0.5 -  0.88  -  0.53
PR - Accuracy - F-measure - Precision:  5360  -  0.5714285969734192 -  0.88  -  0.6133333333333333
PR - Accuracy - F-measure - Precision:  5361  -  0.625 -  0.88  -  0.6752380952380952
PR - Accuracy - F-measure - Precision:  5363  -  0.30000001192092896 -  0.72  -  0.305
PR - Accuracy - F-measure - Precision:  5382  -  0.5454545617103577 -  0.8000000000000002  -  0.58
PR - Accuracy - F-measure - Precision:  5385  -  0.25 -  0.76  -  0.1907936507936508
PR - Accuracy - F-measure - Precision:  5389  -  0.4444444477558136 -  0.8000000000000002  -  0.56
PR - Accuracy - F-measure - Precision:  5392  -  0.5 -  0.8399999999999999  -  0.5771428571428572
PR - Accuracy - F-measure - Precision:  5395  -  0.0 -  0.76  -  0.04
PR - Accuracy - F-measure - Precision:  5410  -  0.25 -  0.64  -  0

In [46]:
## for debug

In [47]:
acc[0]

0.4444444477558136

In [48]:
general = ["XML"
,"Concurrency"
,"HTTP"
,"Network"
,"Memory"
,"OpenOffice Documents"
,"CommandLine"
,"Utils"
,"Throws"
,"Dependency"
,"Logging"
,"Latex"
,"Data Structure"
,"Utility"
,"Test"
,"Runtime"
,"JDK"
,"IO"
,"UI"
,"Annotation "
,"Security"
,"User Preferences"
,"Database"
,"Data"
,"Monitoring"
,"Text Utility"]

In [49]:
general = ["XML"
,"Concurrency"
,"HTTP"
,"Network"
,"Memory"
,"OpenOfficeDocuments"
,"CommandLine"
,"Utils"
,"Throws"
,"Dependency"
,"Logging"
,"Latex"
,"DataStructure"
,"Utility"
,"Test"
,"Runtime"
,"JDK"
,"IO"
,"UI"
,"Annotation "
,"Security"
,"UserPreferences"
,"Database"
,"Data"
,"Monitoring"
,"TextUtility"]

In [50]:
general[0]

'XML'

In [51]:
true1.head(3)

0                                                  1
0  3778          Utils-DataStructure-Network-IO-Logging-UI
1  3783  Throws-Logging-IO-DataStructure-Network-Utils-...
2  3784          Logging-Network-Utils-UI-IO-DataStructure

In [52]:
true1.columns

Index(['0', 1], dtype='object')

In [53]:
true1.shape


(492, 2)

In [54]:
true1.rename(columns={'0':'pr',
                          1:'api'}, 
                 inplace=True)

In [55]:
true1.head(3)

pr                                                api
0  3778          Utils-DataStructure-Network-IO-Logging-UI
1  3783  Throws-Logging-IO-DataStructure-Network-Utils-...
2  3784          Logging-Network-Utils-UI-IO-DataStructure

In [57]:
rslt_df = true1.loc[true1['api'].str.find("Utils") != -1]

In [58]:
rslt_df.head()

pr                                                api
0  3778          Utils-DataStructure-Network-IO-Logging-UI
1  3783  Throws-Logging-IO-DataStructure-Network-Utils-...
2  3784          Logging-Network-Utils-UI-IO-DataStructure
3  3785          IO-UI-Utils-DataStructure-Network-Logging
5  3790          Logging-Utils-IO-Network-UI-DataStructure

In [59]:
## individual metrics for labels

In [60]:
acc_apis = array("f") 
precision_apis = array("f")
f_measure_apis = array("f")
count_api = 0
dataout = []
for i in general: 
    count = 0
    acc_api = 0
    precision_api = 0
    f_measure_api = 0

    for index, row in true1.iterrows():
        #print(index)
        
        api = row["api"]
        if api.find(i)!= -1:
            #print (i, index, row["pr"], row["api"], acc[index], acc_api)
            count = count +1
            acc_api = acc_api + acc[index]
            f_measure_api = f_measure_api + fm[index]
            precision_api = precision_api + pr[index]
    if count != 0:
        print(i, acc_api, count, acc_api/count)
        print(i, f_measure_api, count, f_measure_api/count)
        print(i, precision_api, count, precision_api/count)
        acc_apis.append(acc_api/count)
        f_measure_apis.append(f_measure_api/count)
        precision_apis.append(precision_api/count)

        dataout.append( (i, acc_api/count, f_measure_api/count,  precision_api/count )) 
    else:
        dataout.append( (i, 0, 0,  0 )) 
        print("PR: ", i, " w count = zero!!!")
        print(i, acc_api, count, 0)
        print(i, f_measure_api, count, 0)
        print(i, precision_api, count, 0)
        acc_apis.append(0)
        f_measure_apis.append(0)
        precision_apis.append(0)

    count_api = count_api + 1

df_out = pd.DataFrame(dataout, columns = ['general','acc','f-measure','precision']) 
#df_out.to_csv('./data/Generalmetrics.csv', encoding='utf-8', header=False, index=False, sep=',')    
df_out.to_csv('./data/Generalmetrics2x2NBS.csv', encoding='utf-8', index=False, sep=',')    
np.savetxt(r'./data/Generalmetrics2x2NBS.txt', df_out.values, fmt='%s', delimiter=',')
        
    

XML 9.801150009036064 30 0.32670500030120214
XML 20.36000008881092 30 0.6786666696270307
XML 16.17488430440426 30 0.5391628101468087
Concurrency 17.85828059911728 45 0.396850679980384
Concurrency 33.04000009596348 45 0.7342222243547439
Concurrency 26.792493417859077 45 0.5953887426190906
HTTP 13.19289779663086 40 0.3298224449157715
HTTP 27.920000061392784 40 0.6980000015348196
HTTP 20.345036581158638 40 0.508625914528966
Network 83.89794667065144 195 0.43024588036231504
Network 151.7199999243021 195 0.7780512816630877
Network 108.34663663804531 195 0.5556237776310016
Memory 0.4000000059604645 1 0.4000000059604645
Memory 0.6399999856948853 1 0.6399999856948853
Memory 0.7599999904632568 1 0.7599999904632568
OpenOfficeDocuments 0.8579889535903931 3 0.28599631786346436
OpenOfficeDocuments 1.280000016093254 3 0.4266666720310847
OpenOfficeDocuments 2.5779889822006226 3 0.8593296607335409
CommandLine 5.036773286759853 16 0.31479833042249084
CommandLine 10.480000004172325 16 0.6550000002607703