In [8]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import f1_score, average_precision_score

In [80]:
dfPre = pd.read_csv('./data/predict.csv',header=0,dtype=int,index_col=0)
dfCla = pd.read_csv('./data/classes.csv',sep=';',index_col=0,header=None).loc[dfPre.index]



In [81]:
dfPre.head()

0.1  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15  16  17
0                                                                     
10008     1  0  0  0  0  0  1  0  0  0   1   0   0   0   1   0   1   0
10012     1  0  0  0  1  0  0  0  1  0   0   0   0   0   0   0   0   0
10017     0  0  0  0  0  0  0  0  0  1   0   0   0   0   0   0   0   0
100183    1  0  0  0  0  0  0  0  0  0   0   0   0   0   1   0   0   0
10019     1  1  0  0  0  0  1  0  0  0   0   0   0   0   0   0   1   0

In [82]:
dfPre.shape

(2119, 18)

In [83]:
dfPre.index

Int64Index([ 10008,  10012,  10017, 100183,  10019,  10020,  10023, 100241,
            100271,  10047,
            ...
              9922,   9924,    993,   9944,   9959,    996,   9966,   9968,
              9978,   9989],
           dtype='int64', name='0', length=2119)

In [84]:
dfCla.head()

1
0                             
10008          Horror-Thriller
10012            Comedy-Horror
10017   Action-Science_Fiction
100183           Action-Horror
10019   Comedy-Fantasy-Romance

In [85]:
dfCla.shape

(2119, 1)

In [86]:
dfCla.index

Int64Index([ 10008,  10012,  10017, 100183,  10019,  10020,  10023, 100241,
            100271,  10047,
            ...
              9922,   9924,    993,   9944,   9959,    996,   9966,   9968,
              9978,   9989],
           dtype='int64', name='0', length=2119)

In [87]:
dfCla['valid'] = np.where(dfCla.index==dfPre.index, True, False)

In [88]:
valid = np.where(dfCla.valid==True)


In [89]:
len(valid[0])

2119

In [90]:
valid[0]

array([   0,    1,    2, ..., 2116, 2117, 2118])

In [91]:
dfCla

1  valid
0                                          
10008                Horror-Thriller   True
10012                  Comedy-Horror   True
10017         Action-Science_Fiction   True
100183                 Action-Horror   True
10019         Comedy-Fantasy-Romance   True
...                              ...    ...
996     Crime-Drama-Mystery-Thriller   True
9966         Horror-Mystery-Thriller   True
9968              Comedy-Crime-Drama   True
9978         Action-Adventure-Family   True
9989              Action-Crime-Drama   True

[2119 rows x 2 columns]

In [120]:


def metric():
    columns = ['Accuracy','F-Score','AUC-PR']

    #predictions = pd.read_csv('./data/predict_file1x4.csv',header=0,dtype=int,index_col=0)
    predictions = pd.read_csv('./data/predict_file_20.csv',header=0,dtype=int,index_col=0)
    y_pred = predictions.values
    probabilities = pd.read_csv('./data/probability_file_20.csv',header=0,dtype=float,index_col=0)
    y_proba = probabilities.values

    true = pd.read_csv('./data/PRClasses_20.csv',sep=';',index_col=0,header=None).loc[predictions.index]
    values = [x[0].split('-') for x in true.values]
    mlb = MultiLabelBinarizer()
    y_true = mlb.fit_transform(values)
    
    #Accuracy
    acc_ml = accuracy_ml(y_pred,y_true)
    #F1-Score
    fmeasure_score = f1_score(y_pred,y_true, average='micro')
    #AUC-PR
    pr_score = average_precision_score(y_true,y_proba,average='micro')

    arr = [acc_ml,fmeasure_score,pr_score]

    df = pd.DataFrame([arr],columns=columns)

    print(df)

def accuracy_ml(y_pred,y_true):
    y = y_true == 1
    y_t = [[index for index, value in enumerate(data) if value == 1] for data in y_true]
    y_p = [[index for index, value in enumerate(data) if value == 1] for data in y_pred]
    acc = 0
    for i in range(len(y_t)):
        s,t = set(y_t[i]),set(y_p[i])
        union = s.union(t)
        intersection = s.intersection(t)
        acc += (len(intersection)/len(union))
    return acc/len(y_t)

In [121]:
metric()

   Accuracy  F-Score  AUC-PR
0       1.0      1.0     1.0


In [106]:

def accuracy_ml(y_pred,y_true):
    y = y_true == 1
    y_t = [[index for index, value in enumerate(data) if value == 1] for data in y_true]
    y_p = [[index for index, value in enumerate(data) if value == 1] for data in y_pred]
    acc = 0
    for i in range(len(y_t)):
        s,t = set(y_t[i]),set(y_p[i])
        union = s.union(t)
        intersection = s.intersection(t)
        acc += (len(intersection)/len(union))
    return acc/len(y_t)



In [122]:
columns = ['Accuracy','F-Score','AUC-PR']

#predictions = pd.read_csv('./data/predict_file1x4.csv',header=0,dtype=int,index_col=0)
predictions = pd.read_csv('./data/predict_file_20.csv',header=0,dtype=int,index_col=0)
y_pred = predictions.values
probabilities = pd.read_csv('./data/probability_file_20.csv',header=0,dtype=float,index_col=0)
y_proba = probabilities.values

In [123]:
true = pd.read_csv('./data/PRClasses_20.csv',sep=';',index_col=0,header=None).loc[predictions.index]
values = [x[0].split('-') for x in true.values]
mlb = MultiLabelBinarizer()
y_true = mlb.fit_transform(values)

In [124]:
values

[['Throws',
  'Logging',
  'UI',
  'UserPreferences',
  'Utils',
  'DataStructure',
  'IO',
  'Network'],
 ['IO',
  'Utils',
  'Throws',
  'Logging',
  'Network',
  'UI',
  'UserPreferences',
  'DataStructure'],
 ['DataStructure', 'Utils'],
 ['Utils', 'TextUtility', 'IO', 'DataStructure'],
 ['Concurrency', 'Logging', 'DataStructure'],
 ['IO',
  'Network',
  'UserPreferences',
  'Logging',
  'DataStructure',
  'UI',
  'Throws',
  'Utils',
  'Dependency'],
 ['DataStructure', 'IO', 'Logging', 'UI', 'Dependency', 'Utils'],
 ['IO', 'Utils', 'DataStructure', 'Logging'],
 ['DataStructure', 'Utils'],
 ['Logging', 'Data', 'DataStructure', 'XML'],
 ['Utils'],
 ['Utils', 'DataStructure'],
 ['DataStructure',
  'Network',
  'Utils',
  'UI',
  'IO',
  'Logging',
  'Throws',
  'UserPreferences'],
 ['IO',
  'Network',
  'UI',
  'DataStructure',
  'Throws',
  'Logging',
  'UserPreferences',
  'Utils'],
 ['Network',
  'DataStructure',
  'Logging',
  'UI',
  'UserPreferences',
  'IO',
  'Utils',
  'Throw

In [125]:
y_true

array([[0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0],
       [1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0]])

In [126]:
type(y_true)

numpy.ndarray

In [127]:
y_true.shape

(19, 13)

In [128]:
y_proba


array([[0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0.],
       [0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0.],
       [0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0.],
       [0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0.],
       [0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0.],
       [0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1., 1., 0.],
       [0., 0., 1., 0., 

In [129]:
y_proba.shape

(19, 13)

In [130]:
y_pred

array([[0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0],
       [1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0]])

In [131]:
y_pred.shape

(19, 13)

In [132]:
#Accuracy
acc_ml = accuracy_ml(y_pred,y_true)

In [133]:
#F1-Score
fmeasure_score = f1_score(y_pred,y_true, average='micro')

In [134]:
#AUC-PR
pr_score = average_precision_score(y_true,y_proba,average='micro')
